### ISSUE TITLE
Add example using Auth class

### ISSUE THREAD

**Issue by quantoid** [atlassian/asap-authentication-python#51]
Another way to use this is to create an ASAP authentication class:

    class ASAPAuth(JWTAuth):
        """
        For ASAP authenticating REST requests to a given audience.
        """
        signer = JWTAuthSigner(
            issuer=getenv("ASAP_ISSUER"),
            private_key_retriever=DataUriPrivateKeyRetriever(getenv("ASAP_PRIVATE_KEY")),
        )

        def __init__(self, audience):
            super(ASAPAuth, self).__init__(self.signer, audience)

In this example the private key is a `data:...` URI and all requests come from the same issuer.

Then use it in requests: `auth=ASAPAuth("target-audience")`

**Comment by dbaxa** [comment]
You should be able to use `DataUriPrivateKeyRetriever` to convert a private key provided in an environmental variable to a private key pem (and matching key identifier) & then use JWTAuth like this

```
    import os

    import atlassian_jwt_auth
    from atlassian_jwt_auth.keys import DataUriPrivateKeyRetriever
    from atlassian_jwt_auth.contrib.requests import JWTAuth

    expected_issuer = os.environ.get('ASAP_ISSUER')
    key_id, private_key_pem = DataUriPrivateKeyRetriever(os.environ.get('ASAP_PRIVATE_KEY')).load(expected_issuer)
    signer = atlassian_jwt_auth.create_signer('issuer', 'issuer/key', private_key_pem)
    response = requests.get(
        'https://your-url',
        auth=JWTAuth(signer, 'audience')
    )

```

**Comment by quantoid** [comment]
Yeah, my code will parse the private key every time you sign a request, which is bad. This package requires considerable mental gymnastics to work out how to avoid that.

Best I could come up with:

    class ASAPAuth(JWTAuth):
        """
        For ASAP authenticating REST requests to a particular audience.
        """
        # Use retriever to parse private key once and give result to signer
        # using static retriever to return the same values for every request.
        signer = create_signer(
            settings.ASAP_ISSUER,
            *DataUriPrivateKeyRetriever(settings.ASAP_PRIVATE_KEY).load(settings.ASAP_ISSUER)
        )

        def __init__(self, audience):
            super(ASAPAuth, self).__init__(self.signer, audience)
